[package]
name = "my_todo_list"
version = "1.0.0"
authors = []

[addresses]
todolist_addr='5d4a5002257652b7e1f7ae9cf53c27364dc0c6ae28c3d19e78acb719984392a9'

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
